name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Backend Steps
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Test Backend
        working-directory: backend
        run: npm test # Optional if tests exist

      - name: Build Backend
        working-directory: backend
        run: npm run build

      # Frontend Steps
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            ./k8s/backend-deployment.yaml
            ./k8s/frontend-deployment.yaml
            ./k8s/service.yaml
          images: |
            superno-backend:${{ github.sha }}
            superno-frontend:${{ github.sha }}
