name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Navigate to Backend Directory
        run: cd backend

      - name: Install Backend Dependencies
        run: npm install

      - name: Build Backend
        run: npm run build

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Navigate to Frontend Directory
        run: cd frontend

      - name: Install Frontend Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build
